### PR TITLE
fix(bootstrap): restore TPM FDE messaging

### LINKED ISSUE #743: Restore TPM FDE message
While implementing the new UI for the 'advanced storage features' dialog the message explaining why TPM FDE isn't available got lost. Instead the option is just hidden if it's not supported.
We should restore the behavior of the 23.10 installer and expose message provided by subiquity's `GuidedDisallowedCapabilityReason`.

### PR DESCRIPTION
**Pull request by d-loose**
image

@anasereijo this restores the message as a subtitle and looks the same as in 23.10. We can iterate on the design later if you have suggestions for improvements.

Fix #743
UDENG-2941

### CODE REVIEW

File: packages/ubuntu_bootstrap/lib/installer.dart [hunk 1]
```diff
@@ -37,11 +37,10 @@ Future<void> runInstallerApp(
...
     );
-    parser.addOption(
-      'dry-run-config',
-      valueHelp: 'path',
-      help: 'Path of the dry-run config file',
-    );
+    parser.addOption('dry-run-config',
+        valueHelp: 'path',
+        help: 'Path of the dry-run config file',
+        defaultsTo: 'examples/dry-run-configs/tpm.yaml');
```
Comment (spydon) [inline packages/ubuntu_bootstrap/lib/installer.dart:43]: Why no trailing comma no more? 😭

**Review by spydon — APPROVED** [review]
Lgtm!

**Comment by anasereijo** [comment]
Nitpicking, but if not too much work could you disable the 'Experimental' label? Thank you!
